spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://192.168.1.77:5433/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8081

########################################
# Kafka
########################################

spring.kafka.bootstrap-servers=192.168.1.77:9092

##################################################
# Kafka Producer
##################################################

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
