spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/iogurter/microservices-config.git
          default-label: main
          clone-on-start: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    hostname: 192.168.1.77
    prefer-ip-address: false

    non-secure-port-enabled: true
    non-secure-port: ${server.port}

    home-page-url: http://192.168.1.77:${server.port}/
    status-page-url: http://192.168.1.77:${server.port}/actuator/info
    health-check-url: http://192.168.1.77:${server.port}/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Config Server
    description: Spring Cloud Config Server
    version: 1.0.0
