spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/iogurter/microservices-config.git
          default-label: main
          clone-on-start: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    hostname: config-server
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Config Server
    description: Spring Cloud Config Server
    version: 1.0.0
