services:

  postgres:
    image: postgres:${POSTGRES_VERSION}

    container_name: lab-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - lab-postgres-data:/var/lib/postgresql/data

    networks:
      - lab-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:${REDIS_VERSION}

    container_name: lab-redis

    restart: unless-stopped

    command: >
      redis-server
      --appendonly yes

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - lab-redis-data:/data

    networks:
      - lab-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-insight:
    image: redis/redisinsight:${REDIS_INSIGHT_VERSION}

    container_name: lab-redis-insight

    restart: unless-stopped

    ports:
      - "${REDIS_INSIGHT_PORT}:5540"

    volumes:
      - lab-redis-insight-data:/data

    networks:
      - lab-network

    depends_on:
      redis:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"