services:

  postgres:
    image: postgres:${POSTGRES_VERSION}

    container_name: lab-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - lab-postgres-data:/var/lib/postgresql/data

    networks:
      - lab-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:${REDIS_VERSION}

    container_name: lab-redis

    restart: unless-stopped

    command: >
      redis-server
      --appendonly yes

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - lab-redis-data:/data

    networks:
      - lab-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-insight:
    image: redis/redisinsight:${REDIS_INSIGHT_VERSION}

    container_name: lab-redis-insight

    restart: unless-stopped

    ports:
      - "${REDIS_INSIGHT_PORT}:5540"

    volumes:
      - lab-redis-insight-data:/data

    networks:
      - lab-network

    depends_on:
      redis:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}

    container_name: lab-kafka

    restart: unless-stopped

    hostname: kafka

    ports:
      - "${KAFKA_PORT}:9092"

    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

      KAFKA_NODE_ID: ${KAFKA_NODE_ID}

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@kafka:${KAFKA_CONTROLLER_PORT}

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    volumes:
      - lab-kafka-data:/var/lib/kafka/data

    networks:
      - lab-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1"
        ]
      interval: 15s
      timeout: 10s
      retries: 10

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
